// <auto-generated />
using System;
using CNPM_TTN.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CNPM_TTN.Migrations
{
    [DbContext(typeof(ShopCoffeeContext))]
    [Migration("20260527072910_AddWeightOptionsToProductDetail")]
    partial class AddWeightOptionsToProductDetail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CNPM_TTN.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id")
                        .HasName("PK__Carts__3214EC0729294429");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("FlavorNotes")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GrindingOptionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Weight")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__CartItem__3214EC073FDAD60C");

                    b.HasIndex("GrindingOptionId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex(new[] { "CartId" }, "IX_CartItems_CartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Issuer")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__Certific__3214EC0769BA00A6");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Farmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FarmingMethod")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FarmingZoneId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Scale")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Story")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Farmers__3214EC0741117776");

                    b.HasIndex("FarmingZoneId");

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.FarmerCertification", b =>
                {
                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<int>("CertificationId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.HasKey("FarmerId", "CertificationId")
                        .HasName("PK__FarmerCe__C238F6D017DBAD49");

                    b.HasIndex("CertificationId");

                    b.ToTable("FarmerCertifications");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.FarmingZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Altitude")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Climate")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoilType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK__FarmingZ__3214EC07FA99CF09");

                    b.ToTable("FarmingZones");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.GrindingOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("GrindingOptions");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.HarvestBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("FarmerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("HarvestDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProcessingMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("QualityScore")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__HarvestB__3214EC07BFCBDEB5");

                    b.HasIndex("FarmerId");

                    b.HasIndex("RawMaterialId");

                    b.HasIndex(new[] { "BatchCode" }, "UQ__HarvestB__B22ADA8E5C80BC6E")
                        .IsUnique();

                    b.ToTable("HarvestBatches");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.InventoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("NewQuantity")
                        .HasColumnType("int");

                    b.Property<int>("OldQuantity")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("InventoryLogs");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.InventoryReceipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("HarvestBatchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime");

                    b.Property<double>("Quantity")
                        .HasColumnType("float");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<double>("RemainingQuantity")
                        .HasColumnType("float");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("HarvestBatchId");

                    b.HasIndex("RawMaterialId");

                    b.ToTable("InventoryReceipts");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.LoyaltyPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_LoyaltyPoints_UserId");

                    b.ToTable("LoyaltyPoints");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("FinalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReceiverEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingDetailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShippingDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingNote")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShippingProvince")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingWard")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VoucherCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserId" }, "IX_Orders_UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FlavorNotes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("GrindingOptionId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Weight")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex(new[] { "OrderId" }, "IX_OrderDetails_OrderId");

                    b.HasIndex(new[] { "ProductId" }, "IX_OrderDetails_ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Products_CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.ProductDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte?>("AcidityLevel")
                        .HasColumnType("tinyint");

                    b.Property<string>("BestTime")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte?>("BitternessLevel")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("BodyLevel")
                        .HasColumnType("tinyint");

                    b.Property<int?>("FarmingZoneId")
                        .HasColumnType("int");

                    b.Property<string>("FlavorNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchTags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Process")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Region")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Roast")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TraceabilityData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WeightOptions")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__ProductD__3214EC07E5557A5E");

                    b.HasIndex("FarmingZoneId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SKU");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__ProductV__3214EC07263252F1");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.RawMaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("kg");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("RawMaterials");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.RawMaterialLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<double>("NewQuantity")
                        .HasColumnType("float");

                    b.Property<double>("OldQuantity")
                        .HasColumnType("float");

                    b.Property<int>("RawMaterialId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ReceiptId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedBy");

                    b.HasIndex("RawMaterialId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("RawMaterialLogs");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.RoastingBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BatchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<double?>("InputWeight")
                        .HasColumnType("float");

                    b.Property<int?>("InventoryReceiptId")
                        .HasColumnType("int");

                    b.Property<double?>("OutputWeight")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RoastDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("RoastLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TraceabilityData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("InventoryReceiptId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("RoastingBatches");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CommitmentEndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("CommitmentMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryDay")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FlavorNotes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("GrindingOptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NextDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingDetailAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShippingDistrict")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingProvince")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingWard")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Weight")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ProductId" }, "IX_Subscriptions_ProductId");

                    b.HasIndex(new[] { "UserId" }, "IX_Subscriptions_UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.SubscriptionConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FlavorNote")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GrindType")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<string>("Weight")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("GrindType");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "SubscriptionId" }, "IX_SubscriptionConfigs_SubscriptionId");

                    b.ToTable("SubscriptionConfigs");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.SubscriptionOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ReceiverName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ReceiverPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SnapshotDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "SubscriptionId" }, "IX_SubscriptionOrders_SubscriptionId");

                    b.ToTable("SubscriptionOrders");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MemberTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Bronze");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UserName" }, "IX_Users_UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.UserAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetailAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ward")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__UserAddr__3214EC07C41E6E9D");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddresses");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("MaxUsage")
                        .HasColumnType("int");

                    b.Property<decimal>("MinOrderValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Code" }, "IX_Vouchers_Code")
                        .IsUnique();

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("ProductGrindingOption", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("GrindingOptionId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "GrindingOptionId");

                    b.HasIndex("GrindingOptionId");

                    b.ToTable("ProductGrindingOptions", (string)null);
                });

            modelBuilder.Entity("VoucherCategory", b =>
                {
                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("VoucherId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("VoucherCategories", (string)null);
                });

            modelBuilder.Entity("VoucherProduct", b =>
                {
                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("VoucherId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("VoucherProducts", (string)null);
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Cart", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Carts_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.CartItem", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Carts");

                    b.HasOne("CNPM_TTN.Entities.GrindingOption", "GrindingOption")
                        .WithMany("CartItems")
                        .HasForeignKey("GrindingOptionId")
                        .HasConstraintName("FK_CartItems_GrindingOptions");

                    b.HasOne("CNPM_TTN.Entities.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Products");

                    b.HasOne("CNPM_TTN.Entities.ProductVariant", "ProductVariant")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductVariantId")
                        .HasConstraintName("FK__CartItems__Produ__339FAB6E");

                    b.Navigation("Cart");

                    b.Navigation("GrindingOption");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Farmer", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.FarmingZone", "FarmingZone")
                        .WithMany("Farmers")
                        .HasForeignKey("FarmingZoneId")
                        .IsRequired()
                        .HasConstraintName("FK__Farmers__Farming__3D2915A8");

                    b.Navigation("FarmingZone");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.FarmerCertification", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.Certification", "Certification")
                        .WithMany("FarmerCertifications")
                        .HasForeignKey("CertificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FarmerCer__Certi__42E1EEFE");

                    b.HasOne("CNPM_TTN.Entities.Farmer", "Farmer")
                        .WithMany("FarmerCertifications")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__FarmerCer__Farme__41EDCAC5");

                    b.Navigation("Certification");

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.HarvestBatch", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.Farmer", "Farmer")
                        .WithMany("HarvestBatches")
                        .HasForeignKey("FarmerId")
                        .IsRequired()
                        .HasConstraintName("FK__HarvestBa__Farme__46B27FE2");

                    b.HasOne("CNPM_TTN.Entities.RawMaterial", "RawMaterial")
                        .WithMany("HarvestBatches")
                        .HasForeignKey("RawMaterialId")
                        .IsRequired()
                        .HasConstraintName("FK__HarvestBa__RawMa__47A6A41B");

                    b.Navigation("Farmer");

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.InventoryLog", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.Product", "Product")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_InventoryLogs_Products");

                    b.HasOne("CNPM_TTN.Entities.User", "User")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_InventoryLogs_Users");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.InventoryReceipt", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.User", "CreatedByNavigation")
                        .WithMany("InventoryReceipts")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_InventoryReceipts_Users");

                    b.HasOne("CNPM_TTN.Entities.HarvestBatch", "HarvestBatch")
                        .WithMany("InventoryReceipts")
                        .HasForeignKey("HarvestBatchId")
                        .HasConstraintName("FK__Inventory__Harve__489AC854");

                    b.HasOne("CNPM_TTN.Entities.RawMaterial", "RawMaterial")
                        .WithMany("InventoryReceipts")
                        .HasForeignKey("RawMaterialId")
                        .IsRequired()
                        .HasConstraintName("FK_InventoryReceipts_RawMaterials");

                    b.Navigation("CreatedByNavigation");

                    b.Navigation("HarvestBatch");

                    b.Navigation("RawMaterial");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.LoyaltyPoint", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.User", "User")
                        .WithMany("LoyaltyPoints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_LoyaltyPoints_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Order", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.OrderDetail", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CNPM_TTN.Entities.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired();

                    b.HasOne("CNPM_TTN.Entities.ProductVariant", "ProductVariant")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductVariantId")
                        .HasConstraintName("FK__OrderDeta__Produ__3493CFA7");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Product", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.ProductDetail", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.FarmingZone", "FarmingZone")
                        .WithMany("ProductDetails")
                        .HasForeignKey("FarmingZoneId")
                        .HasConstraintName("FK__ProductDe__Farmi__498EEC8D");

                    b.HasOne("CNPM_TTN.Entities.Product", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ProductDetails_Products");

                    b.Navigation("FarmingZone");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.ProductVariant", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.Product", "Product")
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__ProductVa__Produ__30C33EC3");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.RawMaterial", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.Category", "Category")
                        .WithMany("RawMaterials")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_RawMaterials_Categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.RawMaterialLog", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.User", "ModifiedByNavigation")
                        .WithMany("RawMaterialLogs")
                        .HasForeignKey("ModifiedBy")
                        .HasConstraintName("FK_RawMaterialLogs_Users");

                    b.HasOne("CNPM_TTN.Entities.RawMaterial", "RawMaterial")
                        .WithMany("RawMaterialLogs")
                        .HasForeignKey("RawMaterialId")
                        .IsRequired()
                        .HasConstraintName("FK_RawMaterialLogs_RawMaterials");

                    b.HasOne("CNPM_TTN.Entities.InventoryReceipt", "Receipt")
                        .WithMany("RawMaterialLogs")
                        .HasForeignKey("ReceiptId")
                        .HasConstraintName("FK_RawMaterialLogs_Receipts");

                    b.Navigation("ModifiedByNavigation");

                    b.Navigation("RawMaterial");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.RoastingBatch", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.InventoryReceipt", "InventoryReceipt")
                        .WithMany("RoastingBatches")
                        .HasForeignKey("InventoryReceiptId")
                        .HasConstraintName("FK_RoastingBatches_InventoryReceipts");

                    b.HasOne("CNPM_TTN.Entities.Product", "Product")
                        .WithMany("RoastingBatches")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_RoastingBatches_Products");

                    b.HasOne("CNPM_TTN.Entities.User", "User")
                        .WithMany("RoastingBatches")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_RoastingBatches_Users");

                    b.Navigation("InventoryReceipt");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Subscription", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.Product", "Product")
                        .WithMany("Subscriptions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Subscriptions_Products");

                    b.HasOne("CNPM_TTN.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Subscriptions_Users");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.SubscriptionConfig", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.GrindingOption", "GrindTypeNavigation")
                        .WithMany("SubscriptionConfigs")
                        .HasForeignKey("GrindType")
                        .HasConstraintName("FK_SubscriptionConfigs_GrindingOptions");

                    b.HasOne("CNPM_TTN.Entities.Product", "Product")
                        .WithMany("SubscriptionConfigs")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_SubscriptionConfigs_Products");

                    b.HasOne("CNPM_TTN.Entities.Subscription", "Subscription")
                        .WithMany("SubscriptionConfigs")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SubscriptionConfigs_Subscriptions");

                    b.Navigation("GrindTypeNavigation");

                    b.Navigation("Product");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.SubscriptionOrder", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.Subscription", "Subscription")
                        .WithMany("SubscriptionOrders")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SubscriptionOrders_Subscriptions");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.UserAddress", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__UserAddre__UserI__37703C52");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProductGrindingOption", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.GrindingOption", null)
                        .WithMany()
                        .HasForeignKey("GrindingOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductGrindingOptions_GrindingOptions");

                    b.HasOne("CNPM_TTN.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductGrindingOptions_Products");
                });

            modelBuilder.Entity("VoucherCategory", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VoucherCategories_Categories");

                    b.HasOne("CNPM_TTN.Entities.Voucher", null)
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VoucherCategories_Vouchers");
                });

            modelBuilder.Entity("VoucherProduct", b =>
                {
                    b.HasOne("CNPM_TTN.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VoucherProducts_Products");

                    b.HasOne("CNPM_TTN.Entities.Voucher", null)
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_VoucherProducts_Vouchers");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("RawMaterials");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Certification", b =>
                {
                    b.Navigation("FarmerCertifications");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Farmer", b =>
                {
                    b.Navigation("FarmerCertifications");

                    b.Navigation("HarvestBatches");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.FarmingZone", b =>
                {
                    b.Navigation("Farmers");

                    b.Navigation("ProductDetails");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.GrindingOption", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("SubscriptionConfigs");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.HarvestBatch", b =>
                {
                    b.Navigation("InventoryReceipts");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.InventoryReceipt", b =>
                {
                    b.Navigation("RawMaterialLogs");

                    b.Navigation("RoastingBatches");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("InventoryLogs");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductDetails");

                    b.Navigation("ProductVariants");

                    b.Navigation("RoastingBatches");

                    b.Navigation("SubscriptionConfigs");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.ProductVariant", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.RawMaterial", b =>
                {
                    b.Navigation("HarvestBatches");

                    b.Navigation("InventoryReceipts");

                    b.Navigation("RawMaterialLogs");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.Subscription", b =>
                {
                    b.Navigation("SubscriptionConfigs");

                    b.Navigation("SubscriptionOrders");
                });

            modelBuilder.Entity("CNPM_TTN.Entities.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("InventoryLogs");

                    b.Navigation("InventoryReceipts");

                    b.Navigation("LoyaltyPoints");

                    b.Navigation("Orders");

                    b.Navigation("RawMaterialLogs");

                    b.Navigation("RoastingBatches");

                    b.Navigation("Subscriptions");

                    b.Navigation("UserAddresses");
                });
#pragma warning restore 612, 618
        }
    }
}
